
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: otahontas/groceria
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.groceria.entrypoints=http"
      - "traefik.http.routers.groceria.rule=Host(`groceria.example.com`)"
      - "traefik.http.middlewares.groceria-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.groceria.middlewares=groceria-https-redirect"
      - "traefik.http.routers.groceria-secure.entrypoints=https"
      - "traefik.http.routers.groceria-secure.rule=Host(`groceria.example.com`)"
      - "traefik.http.routers.groceria-secure.tls=true"
      - "traefik.http.routers.groceria-secure.tls.certresolver=http"
      - "traefik.http.routers.groceria-secure.service=groceria"
      - "traefik.http.services.groceria.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

# Proxy is the network where traefik is configured, see traefik docs for more info
networks:
  proxy:
    external: true
