x-defaults: &defaults
  restart: unless-stopped

services:
  groceria-db:
    <<: *defaults
    container_name: groceria-db
    env_file:
      - ./.env
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    volumes:
      - groceria-db-data:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d/

volumes:
  groceria-db-data:
