version: '3'
services:
  groceria:
    build:
      context: .
      dockerfile: Dockerfile
    image: otahontas/groceria
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - json-server
  json-server:
    image: clue/json-server
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./data/db.json:/data/db.json 

networks:
  internal:
    external: false
