version: '3'
services:
  groceria:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://server
    image: otahontas/groceria
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: false
